id: P008071
initial_creation_type: ocr
source_metadata:
  id: bdr:W12362
  title: བཅོམ་ལྡན་འདས་ཐུབ་པའི་དབང་པོའི་མཛད་པ་མདོ་ཙམ་བརྗོད་པ་མཐོང་བས་དོན་ལྡན་སོགས།
  author: ''
  volumes:
    ec204bd5a7ba45a99b9769f4ee0619dd:
      image_group_id: I1KG9237
      title: ''
      volume_number: 1
      total_pages: 480
ebook_metadata:
  title: བཅོམ་ལྡན་འདས་ཐུབ་པའི་དབང་པོའི་མཛད་པ་མདོ་ཙམ་བརྗོད་པ་མཐོང་བས་དོན་ལྡན་སོགས།
  author: ''
  sku: P008071
  cover: cover.jpg
  layers:
  - pagination
