id: opecha:P008071
initial_creation_type: ocr
source_metadata:
  id: bdr:W12362
  title: བཅོམ་ལྡན་འདས་ཐུབ་པའི་དབང་པོའི་མཛད་པ་མདོ་ཙམ་བརྗོད་པ་མཐོང་བས་དོན་ལྡན་སོགས།
  volume:
    7e19d8107bd744cebcc29fd00f415175:
      image_group_id: I1KG9237
      title: Volume 1 of bcom ldan 'das thub pa'i dbang po'i mdzad pa mdo tsam brjod
        pa mthong bas don ldan sogs/
      volume_number: 1
      total_pages: 480
  author: ''
ebook_metadata:
  title: བཅོམ་ལྡན་འདས་ཐུབ་པའི་དབང་པོའི་མཛད་པ་མདོ་ཙམ་བརྗོད་པ་མཐོང་བས་དོན་ལྡན་སོགས།
  author: ''
  sku: P008071
  cover: cover.jpg
  layers:
  - pagination
