id: P008071
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 12:59:29.519094
source_metadata:
  id: bdr:W12362
  title: བཅོམ་ལྡན་འདས་ཐུབ་པའི་དབང་པོའི་མཛད་པ་མདོ་ཙམ་བརྗོད་པ་མཐོང་བས་དོན་ལྡན་སོགས།
  author: ''
  volumes:
    7e19d8107bd744cebcc29fd00f415175:
      image_group_id: I1KG9237
      title: Volume 1 of bcom ldan 'das thub pa'i dbang po'i mdzad pa mdo tsam brjod
        pa mthong bas don ldan sogs/
      volume_number: 1
      total_pages: 480
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
