id: I51E4E574
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T10:14:47+00:00'
last_modified: '2022-06-08T18:13:22.816902+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W12362
  title: བཅོམ་ལྡན་འདས་ཐུབ་པའི་དབང་པོའི་མཛད་པ་མདོ་ཙམ་བརྗོད་པ་མཐོང་བས་དོན་ལྡན་སོགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    CF54:
      image_group_id: I1KG9237
      title: Volume 1 of bcom ldan 'das thub pa'i dbang po'i mdzad pa mdo tsam brjod
        pa mthong bas don ldan sogs/
      total_pages: 480
      order: 1
      base_file: CF54.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
